name: face
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python==3.5.4
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - pillow
  - matplotlib
  - dlib
  - h5py
  - pandas
  - pytorch
  - torchvision
  - opencv
  - pip:
    - cmake==3.12.0
    - inflection
    - dlib

