name: face
channels:
  - defaults
  - menpo
  - conda-forge
  - pytorch
dependencies:
  - python==3.5.4
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - pillow
  - matplotlib
  - dlib
  - h5py
  - pandas
  - pytorch==0.3.1
  - torchvision==0.2.0
  - opencv==3.2.0
  - pip:
    - cmake==3.12.0
    - inflection
    - dlib

